global using Microsoft.EntityFrameworkCore;
global using Talabat.Core.Entities;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Reflection;
global using System.Text.Json;
global using Talabat.Core.Reposistories.Contract;
global using Talabat.Repository.Data;
global using Talabat.Core.Specifications;
global using StackExchange.Redis;